config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path
from django.urls import re_path
from django.urls import include
from django.views.generic import TemplateView

from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="KODJAZ API",
        default_version='v1',
        description="Description of KODJAZ API",
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    # This is just to make reverse("confirm_email", args=[emailconfirmation.key]) work
    re_path(r'^account-confirm-email/(?P<key>[-:\w]+)/$', TemplateView.as_view(), name='confirm_email'),
    path('', include('courses.urls', namespace='courses')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0),
         name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0),
         name='schema-redoc'),
    path('api/', include('authentication.urls', namespace='authentication')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('cabinet/', include('frontend.urls', namespace='frontend')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from rest_framework import routers

from . import views
from courses.api_views import TrackViewSet
from courses.api_views import UnitViewSet
from courses.api_views import LessonViewSet
from courses.api_views import ExerciseViewSet

from courses.api_views import UserTrackViewSet
from courses.api_views import UserUnitViewSet
from courses.api_views import UserLessonViewSet
from courses.api_views import UserExerciseViewSet
from courses.api_views import UserSubmissionViewSet
from courses.api_views import UserSubscriptionViewSet


app_name = 'courses'

router = routers.SimpleRouter()
router.register(r'api/v1/tracks', TrackViewSet)
router.register(r'api/v1/units', UnitViewSet)
router.register(r'api/v1/lessons', LessonViewSet)
router.register(r'api/v1/exercises', ExerciseViewSet)
router.register(r'api/v1/submissions', UserSubmissionViewSet, basename='Submission')

router.register(r'api/v1/user/tracks', UserTrackViewSet, basename='Track')
router.register(r'api/v1/user/units', UserUnitViewSet)
router.register(r'api/v1/user/lessons', UserLessonViewSet)
router.register(r'api/v1/user/exercises', UserExerciseViewSet)
router.register(r'api/v1/user/submissions', UserSubmissionViewSet, basename='Submission')
router.register(r'api/v1/user/subscriptions', UserSubscriptionViewSet, basename='Subscription')

urlpatterns = [
    path('', views.TracksListView.as_view(), name='tracks_list'),
    path('track/<int:track_id>/', views.UnitsListView.as_view(), name='units_list'),
    path('unit/<int:unit_id>/', views.LessonsListView.as_view(), name='lessons_list'),
    path('lesson/<int:lesson_id>/', views.ExerciseListView.as_view(), name='exercises_list'),
    path('exercise/<int:pk>/', views.ExerciseTemplateView.as_view(), name='exercise'),
    path('create_submission', views.CreateSubmissionView.as_view(), name='create_submission'),
]

urlpatterns += router.urls

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(r'', views.UserListView.as_view(), name='list'),
    path('redirect/', views.UserRedirectView.as_view(), name='redirect'),
    path('update/', views.UserUpdateView.as_view(), name='update'),
    path('<slug:id>/', views.UserDetailView.as_view(), name='detail'),
]

courses/views.py
import jwt
import json

from django.conf import settings
from django.db.models import Sum
from django.http import JsonResponse
from django.contrib.auth import login
from django.contrib.auth import get_user_model
from django.views.generic import CreateView, TemplateView
from django.views.generic.list import ListView

from . models import Track, Unit, Lesson, Exercise, Submission, SubmissionCreationException

User = get_user_model()


class LoginJWTUserMixin:
    """
    This mixin is used to create or log in a user
    which was passed via a JWT token.
    JWT should be created a secret key which is created using
    our secret key (see settings.JWT_SECRET)
    In this particular case we are creating/logging in a Laravel user.
    """
    def get(self, request, *args, **kwargs):
        token = request.GET.get('token')
        if token:
            user_data = jwt.decode(token,
                                   settings.JWT_SECRET,
                                   'HS256')
            first_name = user_data.get('first_name')
            last_name = user_data.get('last_name')
            email = user_data.get('email')
            username = user_data.get('username')
            name = '{} {}'.format(first_name, last_name)
            password = 'bcrypt$' + user_data.get('password')
            if email is not None and password is not None:
                user, _ = User.objects.get_or_create(
                    username=username,
                    first_name=first_name,
                    last_name=last_name,
                    name=name, email=email,
                    password=password)
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            else:
                # TODO(murat): Send info to the JWT sender that the token
                # didn't have all the required data
                pass
        return super().get(self, request, *args, **kwargs)


class TracksListView(LoginJWTUserMixin, ListView):
    template_name = 'courses/tracks_list.html'
    model = Track

    def get_queryset(self):
        qs = super(TracksListView, self).get_queryset()
        return qs.filter(is_published=True)


class UnitsListView(ListView):
    model = Unit
    template_name = 'courses/units_list.html'

    def get_queryset(self):
        qs = super(UnitsListView, self).get_queryset()
        return qs.filter(track__id=self.kwargs['track_id'], is_published=True).order_by('id')


class LessonsListView(ListView):
    model = Lesson
    template_name = 'courses/lessons_list.html'

    def get_queryset(self):
        qs = super(LessonsListView, self).get_queryset()
        return qs.filter(unit__id=self.kwargs['unit_id'], is_published=True).order_by('id')

    def get_context_data(self, **kwargs):
        unit = Unit.objects.get(id=self.kwargs['unit_id'])
        context = super(LessonsListView, self).get_context_data(**kwargs)
        context['lessons_duration'] = self.get_queryset().aggregate(
            Sum('lesson_exercises__duration'))['lesson_exercises__duration__sum']
        context['unit'] = unit
        return context


class ExerciseListView(ListView):
    model = Exercise
    template_name = 'courses/exercise_list.html'

    def get_queryset(self):
        qs = super(ExerciseListView, self).get_queryset()
        return qs.filter(lesson__id=self.kwargs['lesson_id'], is_published=True)

    def get_context_data(self, **kwargs):
        lesson = Lesson.objects.get(id=self.kwargs['lesson_id'])
        context = super(ExerciseListView, self).get_context_data(**kwargs)
        context['lesson_duration'] = self.get_queryset().aggregate(Sum('duration'))['duration__sum'] or '0'
        context['lesson'] = lesson
        return context


class ExerciseTemplateView(TemplateView):
    template_name = 'courses/exercise.html'

    def get_context_data(self, **kwargs):
        context = super(ExerciseTemplateView, self).get_context_data(**kwargs)
        exercise = Exercise.objects.get(id=kwargs['pk'])
        submission = self._get_submission(exercise)
        default_code = self._get_default_code(submission, exercise) or exercise.default_code
        new_context = {
            'object': exercise,
            'lecture': exercise.lecture,
            'instruction': exercise.instruction,
            'hint': exercise.hint,
            'default_code': default_code,
            'unit_test': exercise.unit_test,
            'input_should_contain': exercise.input_should_contain,
            'input_should_not_contain': exercise.input_should_not_contain,
            'input_error_text': exercise.input_error_text,
            'output_should_contain': exercise.output_should_contain,
            'output_should_not_contain': exercise.output_should_not_contain,
            'output_error_text': exercise.output_error_text,
            'outputElementId': settings.OUTPUT_CONTAINER_ID_IN_EXERCISES_TEMPLATE,
            'text_file_content': exercise.text_file_content,
            'programming_language': exercise.lesson.unit.track.programming_language,
            'api_url_root': settings.API_URL_ROOT
        }
        context.update(new_context)
        return context

    def _get_submission(self, obj):
        if not self.request.user.is_authenticated:
            return None
        try:
            return Submission.objects.filter(exercise__id=obj.id, user=self.request.user).last()
        except Submission.DoesNotExist:
            return None

    @staticmethod
    def _get_default_code(submission, exercise):
        if submission:
            return submission.submitted_code
        return exercise.default_code


class CreateSubmissionView(CreateView):
    model = Submission

    def post(self, request, *args, **kwargs):
        data = request.POST
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'not_logged_in': True, 'saved': False})
        exercise = self._get_exercise(data)
        submitted_code = data['submitted_code']
        text_file_content = data['text_file_content']
        passed = json.loads(data['passed'])
        try:
            self.model.create_from_exercise(
                user=user,
                exercise=exercise,
                submitted_code=submitted_code,
                text_file_content=text_file_content,
                passed=passed)
            return JsonResponse({'saved': True})
        except SubmissionCreationException as e:
            return JsonResponse({'saved': False})

    @staticmethod
    def _get_exercise(data):
        exercise = Exercise.objects.get(pk=json.loads(data['exercise']))
        if exercise:
            return exercise
        return JsonResponse({'saved': False})

courses/templates/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head_javascript %}
    {% endblock head_javascript %}
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Kod Jaz{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="learn python interactive online free интерактивный курс онлайн бесплатный курс по программированию">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="x-icon" />

    {% block css %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    {% endblock %}
    {% block additional_css %}
    {% endblock %}


  </head>

  <body>

    <div class="m-b">
      <nav class="navbar navbar-expand-md navbar-dark navbar-static-top bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Kod jaz</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-controls="bs-navbar-collapse-1" aria-expanded="true" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="navbar-collapse collapse" id="bs-navbar-collapse-1">
            <ul class="navbar-nav mr-auto">
                {% block navbar %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'courses:tracks_list' %}">{% trans 'Home' %}</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'courses:tracks_list' %}">{% trans 'About' %}</a>
                  </li>
                {% endblock navbar %}
            </ul>

            <ul class="nav navbar-nav pull-xs-right">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:detail' request.user.id  %}">{% trans "My Profile" %}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign out" %}</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
                <li class="nav-item">
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container px-0">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>

      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


    {% endblock javascript %}

    {% block specific_javascript %}
    {% endblock specific_javascript %}
    <script src="{% static 'js/project.js' %}"></script>
  </body>
</html>