config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path
from django.urls import re_path
from django.urls import include
from django.views.generic import TemplateView

from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="KODJAZ API",
        default_version='v1',
        description="Description of KODJAZ API",
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    # This is just to make reverse("confirm_email", args=[emailconfirmation.key]) work
    re_path(r'^account-confirm-email/(?P<key>[-:\w]+)/$', TemplateView.as_view(), name='confirm_email'),
    path('', include('courses.urls', namespace='courses')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0),
         name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0),
         name='schema-redoc'),
    path('api/', include('authentication.urls', namespace='authentication')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('cabinet/', include('frontend.urls', namespace='frontend')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from rest_framework import routers

from . import views
from courses.api_views import TrackViewSet
from courses.api_views import UnitViewSet
from courses.api_views import LessonViewSet
from courses.api_views import ExerciseViewSet

from courses.api_views import UserTrackViewSet
from courses.api_views import UserUnitViewSet
from courses.api_views import UserLessonViewSet
from courses.api_views import UserExerciseViewSet
from courses.api_views import UserSubmissionViewSet
from courses.api_views import UserSubscriptionViewSet


app_name = 'courses'

router = routers.SimpleRouter()
router.register(r'api/v1/tracks', TrackViewSet)
router.register(r'api/v1/units', UnitViewSet)
router.register(r'api/v1/lessons', LessonViewSet)
router.register(r'api/v1/exercises', ExerciseViewSet)
router.register(r'api/v1/submissions', UserSubmissionViewSet, basename='Submission')

router.register(r'api/v1/user/tracks', UserTrackViewSet, basename='Track')
router.register(r'api/v1/user/units', UserUnitViewSet)
router.register(r'api/v1/user/lessons', UserLessonViewSet)
router.register(r'api/v1/user/exercises', UserExerciseViewSet)
router.register(r'api/v1/user/submissions', UserSubmissionViewSet, basename='Submission')
router.register(r'api/v1/user/subscriptions', UserSubscriptionViewSet, basename='Subscription')

urlpatterns = [
    path('', views.TracksListView.as_view(), name='tracks_list'),
    path('track/<int:track_id>/', views.UnitsListView.as_view(), name='units_list'),
    path('unit/<int:unit_id>/', views.LessonsListView.as_view(), name='lessons_list'),
    path('lesson/<int:lesson_id>/', views.ExerciseListView.as_view(), name='exercises_list'),
    path('exercise/<int:pk>/', views.ExerciseTemplateView.as_view(), name='exercise'),
    path('create_submission', views.CreateSubmissionView.as_view(), name='create_submission'),
]

urlpatterns += router.urls

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(r'', views.UserListView.as_view(), name='list'),
    path('redirect/', views.UserRedirectView.as_view(), name='redirect'),
    path('update/', views.UserUpdateView.as_view(), name='update'),
    path('<slug:id>/', views.UserDetailView.as_view(), name='detail'),
]

courses/views.py
import jwt
import json

from django.conf import settings
from django.db.models import Sum
from django.http import JsonResponse
from django.contrib.auth import login
from django.contrib.auth import get_user_model
from django.views.generic import CreateView, TemplateView
from django.views.generic.list import ListView

from . models import Track, Unit, Lesson, Exercise, Submission, SubmissionCreationException

User = get_user_model()


class LoginJWTUserMixin:
    """
    This mixin is used to create or log in a user
    which was passed via a JWT token.
    JWT should be created a secret key which is created using
    our secret key (see settings.JWT_SECRET)
    In this particular case we are creating/logging in a Laravel user.
    """
    def get(self, request, *args, **kwargs):
        token = request.GET.get('token')
        if token:
            user_data = jwt.decode(token,
                                   settings.JWT_SECRET,
                                   'HS256')
            first_name = user_data.get('first_name')
            last_name = user_data.get('last_name')
            email = user_data.get('email')
            username = user_data.get('username')
            name = '{} {}'.format(first_name, last_name)
            password = 'bcrypt$' + user_data.get('password')
            if email is not None and password is not None:
                user, _ = User.objects.get_or_create(
                    username=username,
                    first_name=first_name,
                    last_name=last_name,
                    name=name, email=email,
                    password=password)
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            else:
                # TODO(murat): Send info to the JWT sender that the token
                # didn't have all the required data
                pass
        return super().get(self, request, *args, **kwargs)


class TracksListView(LoginJWTUserMixin, ListView):
    template_name = 'courses/tracks_list.html'
    model = Track

    def get_queryset(self):
        qs = super(TracksListView, self).get_queryset()
        return qs.filter(is_published=True)


class UnitsListView(ListView):
    model = Unit
    template_name = 'courses/units_list.html'

    def get_queryset(self):
        qs = super(UnitsListView, self).get_queryset()
        return qs.filter(track__id=self.kwargs['track_id'], is_published=True).order_by('id')


class LessonsListView(ListView):
    model = Lesson
    template_name = 'courses/lessons_list.html'

    def get_queryset(self):
        qs = super(LessonsListView, self).get_queryset()
        return qs.filter(unit__id=self.kwargs['unit_id'], is_published=True).order_by('id')

    def get_context_data(self, **kwargs):
        unit = Unit.objects.get(id=self.kwargs['unit_id'])
        context = super(LessonsListView, self).get_context_data(**kwargs)
        context['lessons_duration'] = self.get_queryset().aggregate(
            Sum('lesson_exercises__duration'))['lesson_exercises__duration__sum']
        context['unit'] = unit
        return context


class ExerciseListView(ListView):
    model = Exercise
    template_name = 'courses/exercise_list.html'

    def get_queryset(self):
        qs = super(ExerciseListView, self).get_queryset()
        return qs.filter(lesson__id=self.kwargs['lesson_id'], is_published=True)

    def get_context_data(self, **kwargs):
        lesson = Lesson.objects.get(id=self.kwargs['lesson_id'])
        context = super(ExerciseListView, self).get_context_data(**kwargs)
        context['lesson_duration'] = self.get_queryset().aggregate(Sum('duration'))['duration__sum'] or '0'
        context['lesson'] = lesson
        return context


class ExerciseTemplateView(TemplateView):
    template_name = 'courses/exercise.html'

    def get_context_data(self, **kwargs):
        context = super(ExerciseTemplateView, self).get_context_data(**kwargs)
        exercise = Exercise.objects.get(id=kwargs['pk'])
        submission = self._get_submission(exercise)
        default_code = self._get_default_code(submission, exercise) or exercise.default_code
        new_context = {
            'object': exercise,
            'lecture': exercise.lecture,
            'instruction': exercise.instruction,
            'hint': exercise.hint,
            'default_code': default_code,
            'unit_test': exercise.unit_test,
            'input_should_contain': exercise.input_should_contain,
            'input_should_not_contain': exercise.input_should_not_contain,
            'input_error_text': exercise.input_error_text,
            'output_should_contain': exercise.output_should_contain,
            'output_should_not_contain': exercise.output_should_not_contain,
            'output_error_text': exercise.output_error_text,
            'outputElementId': settings.OUTPUT_CONTAINER_ID_IN_EXERCISES_TEMPLATE,
            'text_file_content': exercise.text_file_content,
            'programming_language': exercise.lesson.unit.track.programming_language,
            'api_url_root': settings.API_URL_ROOT
        }
        context.update(new_context)
        return context

    def _get_submission(self, obj):
        if not self.request.user.is_authenticated:
            return None
        try:
            return Submission.objects.filter(exercise__id=obj.id, user=self.request.user).last()
        except Submission.DoesNotExist:
            return None

    @staticmethod
    def _get_default_code(submission, exercise):
        if submission:
            return submission.submitted_code
        return exercise.default_code


class CreateSubmissionView(CreateView):
    model = Submission

    def post(self, request, *args, **kwargs):
        data = request.POST
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'not_logged_in': True, 'saved': False})
        exercise = self._get_exercise(data)
        submitted_code = data['submitted_code']
        text_file_content = data['text_file_content']
        passed = json.loads(data['passed'])
        try:
            self.model.create_from_exercise(
                user=user,
                exercise=exercise,
                submitted_code=submitted_code,
                text_file_content=text_file_content,
                passed=passed)
            return JsonResponse({'saved': True})
        except SubmissionCreationException as e:
            return JsonResponse({'saved': False})

    @staticmethod
    def _get_exercise(data):
        exercise = Exercise.objects.get(pk=json.loads(data['exercise']))
        if exercise:
            return exercise
        return JsonResponse({'saved': False})

courses/templates/courses/exercise.html
{% extends "base.html" %}
{% load markdown_extras %}
{% load i18n %}
{% load static %}
{% block title %}{% trans 'Exercise' %}{% endblock %}

{% block content %}
{# Success modal start #}
<div id="successModal" class="modal bd-success-modal-sm" tabindex="-1" role="dialog" aria-labelledby="successModal"
     aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-body">
                <div class="container-fluid bd-success-modal-row">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    {% if object.next_exercise.id %}
                        <p>{% trans 'You did it! Now go to the next exercise: ' %}
                        <a href="{% url 'courses:exercise' object.next_exercise.id %}">
                            {{ object.next_exercise.name }}
                        </a></p>
                    {% else %}
                        <p>{% trans 'Congratulations! You have passed all the available exercises in this course!' %}</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{# Success modal end #}
{# Fail modal start #}
<div id="failModal" class="modal bd-fail-modal-sm" tabindex="-1" role="dialog" aria-labelledby="failModal"
     aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-body">
                <div class="container-fluid bd-fail-modal-row">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <div>{% trans 'It seems something went wrong with your code. Look at the errors below:' %}</div>
                    <p>{{ input_error_text | markdown | safe }}</p>
                    <p>{{ output_error_text | markdown | safe }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
{# Fail modal end #}
{# Server error modal start #}
<div id="serverErrorModal" class="modal bd-server-error-modal-sm" tabindex="-1" role="dialog"
     aria-labelledby="serverErrorModal" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-body">
                <div class="container-fluid bd-server-error-modal-sm-row">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    {% trans "We did something wrong on our server. Please, try again later or contact admin" %}<br/>
                </div>
            </div>
        </div>
    </div>
</div>
{# Server error modal end #}
<div class="container-fluid">
    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
        {% endfor %}
    {% endif %}
    <div class="row">
        <div class="col-sm-3">
            <h2>{{ object.name }}</h2>

            <div class="instructions-divider padding-5px">{% trans 'Useful information' %}</div>
            <div class="padding-top-bottom-5px">{{ lecture | markdown | safe }}</div>
            <div class="instructions-divider padding-5px">{% trans 'Instructions' %}</div>
            <div class="padding-top-bottom-5px">{{ instruction | markdown | safe }}</div>
            <div class="instructions-divider padding-5px cursor" id="hintToggle">{% trans 'Need help? Click here.' %}</div>
            <div class="padding-top-bottom-5px hidden" id="hint">
                {% if hint|length > 0 %}
                    {{ hint | markdown | safe }}
                {% endif %}
            </div>
        </div>
        <div class="col-sm-5">
          <ul class="nav nav-tabs mt-1" id="editorsTab" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" id="code-tab" data-toggle="tab" href="#code" role="tab" aria-controls="code" aria-selected="false">
                {% if programming_language == 'Python' %}
                  code.py
                {% elif programming_language == 'JavaScript' %}
                  code.js
                {% elif programming_language == 'TypeScript' %}
                  code.ts
                {% endif %}
              </a>
            </li>
            {% if text_file_content %}
            <li class="nav-item">
              <a class="nav-link" id="file-tab" data-toggle="tab" href="#file" role="tab" aria-controls="file" aria-selected="false">
                file.txt
              </a>
            </li>
            {% endif %}
          </ul>
          <div class="tab-content editor-wrapper" id="editorsTabContent">
            <pre
              class="editor tab-pane fade show active"
              id="code"
              role="tabpanel"
              aria-labelledby="code-tab">{{ default_code }}</pre>
            <pre
              class="editor tab-pane fade"
              id="file"
              role="tabpanel"
              aria-labelledby="file-tab">{{ text_file_content }}</pre>
              <textarea id="file.txt" style="display: none;"></textarea> 
          </div>
          <div class="row padding-top-5px">
            <div class="col-sm-4 padding-bottom-5px">
              <button id="run" type="button" class="btn btn-primary">{% trans 'Run and Check' %}</button>
            </div>
            {% if not request.user.is_authenticated %}
            <div class="col-sm-6 col-sm-offset-1 padding-0">
                <div class="alert alert-warning padding-9px margin-bottom-0 text-xs-center" role="alert">
                    {# Add trans with a context to make it easy to translate #}
                    <a href="{% url 'account_login' %}" class="alert-link">
                        {% trans "Sign in" context "Sign in to save your progress" %}
                    </a> {% trans 'to save your progress' %}
                </div>
            </div>
            {% endif %}
          </div>
        </div>
        <div class="col-sm-4">
            <div class="padding-top-1em output-console">
                <div class="card card-fixed-height">
                    <div class="card-body">
                        <div class="card-text">
                            <pre class="output-pre" id="{{ outputElementId }}"></pre>
                        </div>
                    </div>
                </div>
                <div id="turtle-canvas"></div>
            </div>
        </div>
    </div>
    <div>
        <textarea readonly id="code_checker" style="display: none;">{{ unit_test }}</textarea>
    </div>
</div>
{% endblock content %}

{% block specific_javascript %}

<script src="{% static 'js/skulpt/skulpt.min.js' %}"></script>
<script src="{% static 'js/skulpt/skulpt-stdlib.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.11/ace.min.js" integrity="sha256-qCCcAHv/Z0u7K344shsZKUF2NR+59ooA3XWRj0LPGIQ=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.11/mode-python.min.js" integrity="sha256-dgu7+RV2rby44bxsuQuo2Rm+pG0JXtShrFWStI0DrC4=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.11/mode-javascript.min.js" integrity="sha256-cN39Ofb0/L/HOBScgDuoNefcVF4+MKdAsxXR3g/xyZw=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.11/theme-vibrant_ink.min.js" integrity="sha256-IQ2CFOsaAexyrA3QCiqwFxfqVrl8+x0sXtv2mZqoQgo=" crossorigin="anonymous"></script>
{% if programming_language == 'JavaScript' %}
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
{% elif programming_language == 'TypeScript' %}
  <script src="{% static 'js/typescriptServices.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.11/mode-typescript.min.js" integrity="sha256-+SkRqydbTRTCFyyYwSqfcE3PGTWrrY3UplUDh4aYGUk=" crossorigin="anonymous"></script>
{% endif %}
<script type="text/javascript">
  {% autoescape off %}
  var payload = {
    inputShouldContain: '{{ input_should_contain }}'.split(","),
    inputShouldNotContain: '{{ input_should_not_contain }}'.split(","),
    outputShouldContain: '{{ output_should_contain }}'.split(","),
    outputShouldNotContain: '{{ output_should_not_contain }}'.split(","),
    path: '{% url 'courses:create_submission' %}',
    csrfToken: '{{ csrf_token }}',
    objectId: {{ object.id }},
    outputElementId: "{{ outputElementId }}",
    notLoggedInMessage: "{% trans 'Your progress not saved.' %}",
    programmingLanguage: "{{ programming_language }}",
    worker: "{% static 'js/worker.js' %}",
    api_url_root: "{{ api_url_root }}"
  }
  {% endautoescape %}
</script>
{% endblock specific_javascript %}

courses/templates/courses/exercise_list.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block title %}{% trans 'Exercises' %}{% endblock %}

{% block navbar %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'courses:units_list' lesson.unit.track.id %}">
            {{ lesson.unit.track.name }}
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'courses:lessons_list' lesson.unit.id %}">
            {{ lesson.unit.name }}
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'courses:exercises_list' lesson.id %}">
            {{ lesson.name }}
        </a>
    </li>
{% endblock navbar %}

{% block content %}

    <div class="container">
      <div class="row">
        <h1>{% trans 'Exercises' %}</h1>
        <ul class="list-group list-group-flush w-100">
          <div>{% trans 'Duration:' %} {{ lesson_duration }} {% trans 'min.' %}</div>
          {% for exercise in object_list %}
            <li class="list-group-item list-group-item-action w-100">
              <span><strong>{{ exercise.name }}</strong></span>
              <a href="{% url 'courses:exercise' exercise.id %}">
                <div>{% trans 'Exercise duration:' %} {{ exercise.duration }} {% trans 'min.' %}</div>
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>

{% endblock content %}

courses/templates/courses/lessons_list.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block title %}{% trans 'Lessons' %}{% endblock %}


{% block navbar %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'courses:units_list' unit.track.id %}">
            {{ unit.track.name }}
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'courses:lessons_list' unit.id %}">
            {{ unit.name }}
        </a>
    </li>
{% endblock navbar %}

{% block content %}

    <div class="container">
      <div class="row">
        <div>
          {# Translators: the following would look like this -- Unit 1: Python syntax lessons #}
          <h1>{% trans 'Unit:' %} {{ unit.name }}. {% trans 'Lessons' %}.</h1>
          <div class="padding-bottom-5px">{% trans 'Overall Duration:' %} {{ lessons_duration }} {% trans 'min.' %}</div>
        </div>
          <ul class="list-group list-group-flush w-100">
            {% for lesson in object_list %}
            <li class="list-group-item list-group-item-action w-100">
              <span><strong>{{ lesson.name }}</strong></span>
              <a href="{% url 'courses:exercises_list' lesson.id %}">
                <div class="list-group-item-heading">{% trans 'Number of exercises:' %} {{ lesson.exercises_number }}</div>
                <div class="list-group-item-heading">{% trans 'Duration of exercises:' %} {{ lesson.exercises_duration }} {% trans 'min.' %}</div>
              </a>
            </li>
            {% endfor %}
          </ul>
        </div>
    </div>

{% endblock content %}

courses/templates/courses/tracks_list.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block title %}{% trans 'Tracks' %}{% endblock %}

{% block content %}

    <div class="container">
      <h1>{% trans 'Tracks' %}</h1>
      <div class="row">
        <ul class="list-group list-group-flush w-100">
          {% for track in object_list %}
            <li class="list-group-item list-group-item-action w-100">
              <span><strong>{{ track.name }}</strong></span>
              <a class="w-100" href="{% url 'courses:units_list' track.id %}">
                <div class="list-group-item-heading">{{ track.description }}</div>
                <div class="list-group-item-heading">{% trans 'Number of units:' %} {{ track.units_count }}</div>
                <div class="list-group-item-heading">{% trans 'Number of lessons:' %} {{ track.lessons_count }}</div>
                <div class="list-group-item-heading">{% trans 'Lessons overall duration:' %} {{ track.unit_lessons_duration }}</div>
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>

{% endblock content %}

courses/templates/courses/units_list.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block title %}{% trans 'Units' %}{% endblock %}

{% block navbar %}
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'courses:units_list' object_list.0.track.id %}">
            {{ object_list.0.track.name }}
        </a>
    </li>
{% endblock navbar %}

{% block content %}

<div class="container">
  <h1>{% trans 'Units' %}</h1>
  <div class="row">
    <ul class="list-group list-group-flush w-100">
      {% for unit in object_list %}
        <li class="list-group-item list-group-item-action w-100">
          <span><strong>{{ unit.name }}</strong></span>
          <a class="w-100" href="{% url 'courses:lessons_list' unit.id %}">
            <div class="list-group-item-heading">{{ unit.description }}</div>
            <div class="list-group-item-heading">{% trans 'Number of lessons in unit:' %} {{ unit.lessons_count }}</div>
            <div class="list-group-item-heading">{% trans 'Overall duration of lessons in unit:' %} {{ unit.lessons_exercises_duration }} {% trans 'min.' %}</div>
          </a>
        </li>
      {% endfor %}
    </div>
</div>

{% endblock content %}